spring.application.name=usage-service
server.port=8083

# Kafka - Consumer
spring.kafka.bootstrap-servers=localhost:9094
spring.kafka.consumer.group-id=usage-service

# 1. On utilise le désérialiseur JSON standard (ou ErrorHandlingDeserializer pour plus de robustesse, voir note plus bas)
spring.kafka.consumer.key-deserializer=org.apache.kafka.common.serialization.StringDeserializer
spring.kafka.consumer.value-deserializer=org.springframework.kafka.support.serializer.JsonDeserializer

# 2. On dit au consommateur d'IGNORER l'en-tête __TypeId__ envoyé par l'ingestion-service
spring.kafka.consumer.properties.spring.json.use.type.headers=false

# 3. On force le consommateur à utiliser SA PROPRE classe locale pour mapper le JSON
spring.kafka.consumer.properties.spring.json.value.default.type=com.leetjourney.kafka.event.EnergyUsageEvent

# 4. On autorise explicitement le paquet local du usage-service (bonne pratique de sécurité)
spring.kafka.consumer.properties.spring.json.trusted.packages=com.leetjourney.kafka.event

#Kafka - producer
spring.kafka.template.default-topic=energy-alerts
spring.kafka.producer.key-serializer=org.apache.kafka.common.serialization.StringSerializer
spring.kafka.producer.value-serializer=org.springframework.kafka.support.serializer.JsonSerializer

# Influx DB Configuration
influx.url=http://localhost:8072
influx.token=bhQCCZoYlfSZGnwn0RIk-NHkFbk_-aDbCiUec3Gu50EpV8QVNUtiXIxOx_REhVS1lUbOpJoHhF7MmeyPooZijA==
influx.org=leetjourney
influx.bucket=usage-bucket

device.service.url=http://localhost:8081/api/v1/device
user.service.url=http://localhost:8080/api/v1/user